### ISSUE TITLE
Test cases for Selenium testing of the website

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1311]
These are the proposed test cases which we can check for fixing the regressions:

- [x]  Check whether the name of the event is correct or not
- [x]  Test the links of the navbar. The response code should not be 404.
- [x]  Test the links of the footer. The response code should not be 404.
- [x]  Search is working in both, Starred and All mode. Also, make sure that the search results change instantaneously on adding/removing a character.
- [x]  Tweets are being displayed on the event page.
- [ ]  Subnavbar on rooms and tracks page are working and we get appropriately scrolled down to the relevant section on clicking a link inside it.
- [x]   Clicking and expanding on the session element on all the pages work as expected. The element should collapse and uncollapse predictably.
- [x]  Share button is working.
- [x]  No scrollbars are present on the generated site.
- [x]  The down button which directs users back to the top of the page is working.
- [x]  After expanding the session element, when we click on the speaker picture, we should get redirected to the same speaker on the speaker's page.
- [x]  The track listed on hovering over the speaker's picture should redirect to the same track on the tracks page on clicking.
- [ ]  Check for the color of the font and the color of the tracks and make sure that it is correct.

I will start working on it and open child issues for them. Thanks!!

**Comment by aayusharora** [comment]
Thanks for this. Nice sum up.
