### ISSUE TITLE
Little issues in the generated event sites

### ISSUE THREAD

**Issue by Princu7** [fossasia/open-event-webapp#1338]
Lately, I have been actively testing the samples of the open-event repository regarding events like Facebook Developer Conference, Mozilla All Hands, and Oscon 2017. While generating the samples, I have come across a few issues/bugs:-

- [x] The event background logo doesn't get rendered when the site is generated through the zip sample.
- [x] The text is session element is misaligned when there is no speaker associated with a particular session.
- [ ] The images don't work if they are uploaded to Google cloud storage.
- [x] The default missing speaker photo doesn't appear on the front page in case of featured speakers.
- [x] The position of speakers is missing on all the pages.

I will be opening a separate issue for each of the above bugs and solve them. Thanks!!

**Comment by agbilotia1998** [comment]
@Princu7 please mention the way to reproduce google cloud storage upload error.
