### ISSUE TITLE
Add more Selenium tests

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-webapp#1614]
Add more tests for schedule, tracks, rooms & speakers page. 

- [ ] Add tests for sessions on each page check speaker, type of session, background color etc.
- [ ] Add tests for social links (Tests for Buttons already exist) also add test to check url for sharing next to social buttons.
- [ ] Add test for download dropdown on schedule page.
- [ ] Add tests for speakers page for hover state.
- [ ] Add tests for social links on the top bar & footer
- [ ] Add tests for tracks name
- [ ] Add tests for sponsors on event page.

@agbilotia1998 @ParthS007 Have a look at this, add more if I missed something.

**Comment by agbilotia1998** [comment]
Okay @geekyd will work on it.

**Comment by geekyd** [comment]
@agbilotia1998 @ParthS007 Please create sub issues for the test you want to add.

**Comment by agbilotia1998** [comment]
Okay!

**Comment by agbilotia1998** [comment]
@geekyd can you please elaborate more on 'Add tests for tracks name'

**Comment by agbilotia1998** [comment]
@geekyd also 'Add tests for social links on the top bar & footer' is already there , please check once.

**Comment by ParthS007** [comment]
@geekyd Sorry, I was not well for past few days hence not able to give PR on this issue. I will first work on #1601 and then will give PR of remaining tests. BTW, Great work @agbilotia1998 🎉
