### ISSUE TITLE
Create Simple First Version for Web App Generator

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-webapp#203]
The web app generation can be bundled with the orga server, but it should also be possible to generate web apps just by getting the data from a JSON file. As a first step we need a simple web page, where an organizer can choose to upload a JSON file and generate the app that can be downloaded as a zip file. The first version is similar to a graphical implementation of the Open Event Scraper (https://github.com/fossasia/open-event-scraper) with zip download, but should include additional design features in follow up versions including choosing a color scheme and theme.

* [x] Webapp Generator Component 1: Create a Web Page with Form Elements to upload. https://github.com/fossasia/open-event-webapp/issues/238
* [x] Webapp Generator Component 2: Add Upload Functionality to Server of JSON files, schedule, speakers etc. Must be able to receive and store data entered by a user on the website https://github.com/fossasia/open-event-webapp/issues/230
* [x] Webapp Generator Component 3: Create a Script to generate a web app https://github.com/fossasia/open-event-webapp/issues/234
* [x] Webapp Generator Component 4: Implement function to call or trigger the script to build and the web app after upload of JSON files https://github.com/fossasia/open-event-webapp/issues/235
* [x] Webapp Generator Component 5: Allow user to download the entire web app as a zip https://github.com/fossasia/open-event-webapp/issues/236
* [x] Webapp Generator Component 6: Additionally offer option to call from a REST API URL later for hosted mode instead of uploading JSON files https://github.com/fossasia/open-event-webapp/issues/237

![selection_032](https://cloud.githubusercontent.com/assets/6565270/15830700/6f7881dc-2c37-11e6-8c84-df1aa4f83f62.png)
(Compare to Android App Generator: https://github.com/fossasia/open-event-android/issues/382)

**Comment by juslee** [comment]
To paraphrase @mariobehling:

- Give me a UI/User flow ASAP
- Construct with a UI and layout (genetella)
- Read a JSON and display the data
- Allow me to download the entire web app project in a zip with the JSON (which is the EASIEST once you have DONE the UI/User flow)
- Call from a REST API URL later for hosted mode

@championswimmer @aayusharora understand?

**Comment by championswimmer** [comment]
@juslee 
**gentelella** is a "Admin template" suitable for making dashboards, analytics panels etc
For the client-side webapp (that will be *viewed* by attendees), why do we need to use gentelella?

**Comment by juslee** [comment]
@championswimmer then suggest a new theme to use. Otherwise, use it first for consistency. You can refactor and replace the theme later. You should be able to easily refactor with a bit of work to use a new bootstrap theme. Code that in mind.

**Comment by mariobehling** [comment]
@championswimmer I do hope we will get started with this now. Please separate this issue into issues that can be done in a single day. We can use the part of the current Open Event Scraper to generate an app from a JSON. Then generate a schedule just like http://2016.opentechsummit.net/programm/ Once this is working you can change it to gentelella or another bootstrap theme, but please do start to get this going now. You can also do differently, but please start.

**Comment by championswimmer** [comment]
@mariobehling

Yes will get started right away

**Comment by championswimmer** [comment]
@mariobehling 

https://github.com/OpenTechSummit/open-event-scraper has audio support now. 
It is in a state to be used to generate simple schedule page with sessions and speakers. 

For the purpose of having a generated static html based website for events, we have it now.

**Comment by mariobehling** [comment]
@championswimmer What is the status on this? When do we have a UI to generate the web app?

**Comment by mariobehling** [comment]
See sample here:
![screenshot from 2016-05-31 17 18 23](https://cloud.githubusercontent.com/assets/1583873/15680096/9588934a-2754-11e6-8fb8-b039d7ae3707.png)

**Comment by aayusharora** [comment]
View 
![9](https://cloud.githubusercontent.com/assets/12194719/15835091/1d7d59ca-2c37-11e6-9478-8e6f4ef07717.png)
Solved here #227 , will be opening issues for adding functionality .

**Comment by championswimmer** [comment]
All done
