### ISSUE TITLE
Implement feature to deploy the webapp online directly from generator page

### ISSUE THREAD

**Issue by aayusharora** [fossasia/open-event-webapp#275]
* [ ] Implement UI and backend to enter Github credentials and deploy to Github Pages https://github.com/fossasia/open-event-webapp/issues/506
* [x] Deploy to web server via ftp

**Comment by championswimmer** [comment]
We will take this in two steps. 

- [ ] write docs on how user can manually upload the zip contents to gh-pages.
- [ ] created automated interface to upload to gh-pages (will ask user to sign-in via github)

**Comment by mariobehling** [comment]
Why do we need docs how a user can manually upload to gh-pages? Isn't there enough documentation on GitHub already?

**Comment by championswimmer** [comment]
At least we should link to such documentation in our README.
