### ISSUE TITLE
Suport for images/audio in zip, in api and as external links

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-webapp#522]
So we need to support all three cases here 

- [x] images/audio are relative paths in the API itself and we have to download
- [x] images/audio are external links that we have to download (already supported)
- [x] images/audio are uploaded with the zip file (sub-issue #520)

**Comment by championswimmer** [comment]
we will have case 3 done when this issue https://github.com/fossasia/open-event-webapp/issues/520 is solved

**Comment by aayusharora** [comment]
@championswimmer Case 3 is done https://github.com/fossasia/open-event-webapp/pull/521

**Comment by aayusharora** [comment]
@championswimmer  Can you please help me in this  **images/audio are relative paths in the API itself and we have to download** ?

**Comment by championswimmer** [comment]
point no.1 done here https://github.com/fossasia/open-event-webapp/issues/522
